### ISSUE TITLE
Vendor files doesn't work after moving into abstract env

### ISSUE THREAD

**Issue by maZahaca** [redco/goose-phantom-environment#9]
After that change https://github.com/redco/goose-phantom-environment/blob/master/lib/PhantomEnvironment.js#L681

PhantomJS cannot inject files properly

**Comment by maZahaca** [comment]
I've tried http://phantomjs.org/api/webpage/property/library-path.html, but it has no success. But probably I did something wrong

**Comment by jifeon** [comment]
fixed here https://github.com/redco/goose-abstract-environment/pull/2#discussion_r143336640 and here https://github.com/redco/goose-phantom-environment/pull/10
